CREATE TABLE IF NOT EXISTS resources
(
    id    INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    user  INTEGER NOT NULL,
    food  INTEGER NOT NULL DEFAULT 100,
    wood  INTEGER NOT NULL DEFAULT 100,
    stone INTEGER NOT NULL DEFAULT 100,
    gold  INTEGER NOT NULL DEFAULT 100,

    FOREIGN KEY (user) REFERENCES users (id)
);